name: Test

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]

jobs:
  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MODULAR_LOGGER_DEBUG: true

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Initialize Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
      - name: Initialize Node environment
        uses: actions/setup-node@v3
        with:
          node-version: "14.17.0"
      - name: Install Node Dependencies
        run: npm install
      - name: Install Node Dependencies
        run: go install
      - name: Run Tests
        run: go test ./...
      - name: Dry build
        run: npm run build
