name: Test

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]

jobs:
  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      MODULAR_LOGGER_DEBUG: true

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Initialize environment
        uses: 
          - actions/setup-go@v3
          - actions/setup-node@v3
        with:
          go-version: "1.17.0"
          node-version: "14.17.0"
      - name: Install Dependencies
        run: 
          - go install
          - npm install
      - name: Run Tests
        run: go test ./...
      - name: Dry build
        run: npm run build
